apiVersion: v1
kind: Service
metadata:
  name: movieapp-service
  namespace: default
spec:
  selector:
    app: movieapp
  type: NodePort
  ports:
  - name: movieapp
    protocol: TCP
    port: 8080
    targetPort: 8080

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name:  movieapp
  namespace: default
  labels:
    app:  movieapp
spec:
  selector:
    matchLabels:
      app: movieapp
  replicas: 1
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app:  movieapp
    spec:
      # initContainers:
        # Init containers are exactly like regular containers, except:
          # - Init containers always run to completion.
          # - Each init container must complete successfully before the next one starts.
      containers:
      - name:  movieapp
        image:  "bhargodevarya/movieapplication:1.0"
        livenessProbe:
          httpGet:
            port: 8080
            path: /movie/hello
#          tcpSocket:
#            port: 8080
          initialDelaySeconds: 60
          timeoutSeconds: 120
          successThreshold: 1
          failureThreshold: 3
          periodSeconds: 120
        ports:
        - containerPort:  8080
          name:  movieapp-port
          hostPort: 8080
      restartPolicy: Always

---

kind: Service
apiVersion: v1
metadata:
  name: mongo
spec:
  type: ExternalName
  externalName: cloudplaygroundcluster.xvnxrks.mongodb.net