spring:
  data:
    mongodb:
      #host: ds163182.mlab.com
      #port: 63182
      #username: Bhargo_RO
      #password:
      #set while building the image using docker
      uri: mongodb+srv://MovieUser:<pwd>@cloudplaygroundcluster.lxuiq.mongodb.net/MovieDB
      database: MovieDB