spring:
  data:
    mongodb:
      #host: ds163182.mlab.com
      #port: 63182
      #username: Bhargo_RO
      #password:
      #set while building the image using docker
      uri: mongodb+srv://MovieUser:1JlJUTQvbpu3n5hX@cloudplaygroundcluster.xvnxrks.mongodb.net/
      database: sample_mflix
  cloud:
    compatibility-verifier:
      enabled: false

application:
  config:
    data:
      source:
        type: file
        name: sample_mflix.movies.json